# You can find the Snyk Official CLI container images here: https://github.com/snyk/cli#snyk-cli-in-a-docker-image
steps:
  - name: 'snyk/snyk-cli:npm'
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        snyk test --json-file-output=results-open-source.html || true
    id: Snyk Open Source test
    entrypoint: bash
  - name: 'snyk/snyk-cli:npm'
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        snyk code test --sarif-file-output=results-code.html || true
    id: Snyk Code test
    entrypoint: bash
  - name: 'snyk/snyk-cli:npm'
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        snyk iac test <TERRAFORM FILE> --json-file-output=results-iac.html || true
    id: Snyk IaC test
    entrypoint: bash
  - name: 'snyk/snyk-cli:npm'
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        snyk container test <CONTAINER_IMAGE> --json-file-output=results-container.html || true
    id: Snyk Container test
    entrypoint: bash
artifacts:
  objects:
    location: 'gs://<STORE_NAME>/scan_output'
    paths:
      - results-open-source.html
      - results-code.html
      - results-iac.html
      - results-container.html
