# Need to include this in the same directory as your k8s deployment yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync # PreSync hook would allow the below container to run before the actual synchronization
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: snyk-cli
        image: snyk/snyk-cli:npm
        command: ["/bin/sh","-c"]
        args:
          - git clone https://github.com/jiajunngjj/argocd-goof.git
          - snyk auth $SNYK_TOKEN
          - snyk iac test argocd-goof/goof/goof-deployment.yaml --severity-threshold=high # any detection of vuln with severity high and above would fail the synchronization
        env:
          - name: SNYK_TOKEN # Create your Snyk token as a secret in the same namespace that that this job is running
            valueFrom:
              secretKeyRef:
                name: snyk-token
                key: token
      restartPolicy: Never
  backoffLimit: 0
